// Quotes data (replace this with your actual quotes data)
const quotes = {
    'A': [
        'A ballet of the obvious',
        'A beautiful theory killed by some ugly little facts.',
        'A bird teaches a fish to swim, without hatred, without bitterness.',
        'A bond of common laughter.',
        'A bore: someone who deprives you of solitude without providing you with companionship.',
        'A bowling alley with lipstick.',
        'A briefcase with a mouth.',
        'A bull who carries his china closet with him.',
        'A candle loses nothing by lighting another candle.',
        'A career is about taking risks.',
        'A certain sunny shamelessness.',
        'A chain is no stronger than its weakest link.',
        'A champion hates to lose even more than he loves to win.',
        "A change of place changes one's luck.",
        'A child does not despise the bubble because it burst; he immediately sets to work to blow another one.',
        'A child should never have to wonder if his parents love him.',
        'A clarity of vision prompted by the purest form of greed.',
        'A committee is a dark alley down which ideas are led to be strangled.',
        'A company is stronger if it is bound by love rather than fear.',
        "A company is the combined rhythms of intelligent people rather than any one person's particular expertise or brains.",
        'A competitive world has two possibilities for you. You can lose. Or, if you want to win, you can change.',
        'A complicity of needy souls.',
        'A computer does not substitute for judgment any more than a pencil substitutes for literacy. But writing without a pencil is no particular advantage.',
        'A confusion of the real with the ideal never goes unpunished.',
        'A constant battle between sharks and suits.',
        'A continual circulation of lies among those who are not much in the way of hearing them contradicted will in time pass for the truth. (Jefferson)',
        'A corporate culture has to be built on expectations of performance, not rules of behavior.',
        "A critic is a man who knows the way, but can't drive the car.",
        'A crowd is not company.',
        'A culture hollowed out by the imperatives of modern life.',
        'A culture of worthless admirations – unjust praise without purpose or end.',
        'A customer is anyone who can tell you "no".',
        "A cynic is a passionate person who doesn't want to be disappointed again.",
        'A dancing nation, fickle and untrue; have oft undone themselves and others too.',
        'A danger foreseen is half avoided.',
        'A dangerously honest man.',
        'A desk is a dangerous place from which to watch your business.',
        'A devaluation is like wetting your pants. It only feels good for a little while.',
        'A diamond is a chunk of coal that made good under pressure.',
        'A diplomat is a man who thinks twice before he says nothing.',
        "A divorce is like an amputation; you survive, but there's less of you.",
        'A doer in a world of doubters.',
        'A doubtful friend is worse than a certain enemy. Let a man be one or the other, and then we know how to meet him.',
        'A dream is a wish your heart makes.',
        "A driving ambition is of little use if you're on the wrong road.",
        "A drowning man will clutch at a straw.",
        "A drunk keeps no secrets.",
        'A failure is not always a mistake. It may simply be the best one can do under the circumstances. The real mistake is to stop trying.',
        'A few things are important; most are not.',
        'A firm is never static - it is either growing or stagnating.',
        "A fish wouldn't get in trouble if it kept its mouth shut.",
        'A fool and his money are soon parted.',
        'A fool is his own informer.',
        'A fool will lose tomorrow reaching back for yesterday.',
        'A fool throws a stone in a pond and ten sages knock themselves out trying to find it.',
        'A friend has the responsibility to be a witness.',
        'A funeral in the brain.',
        'A general may be sincere, if it serves his purpose, but his purpose is never sincerity.',
        'A goal is a dream with a deadline.',
        'A goal without a plan is just a daydream.',
        'A good action appears inevitable in retrospect.',
        "A good day ain't got no rain. A bad day is when I lie in bed and think of what might have been.",
        'A good deed never goes unpunished.',
        'A good hat can make the difference between a bimbo and a princess.',
        'A good idea and some hard work can make a difference.',
        'A good leader knows himself and his times.',
        'A good leader never blames his people for his failings.',
        'A good plan, violently executed right now, is a lot better than a perfect plan executed next week.',
        'A good scare is worth more to a man than good advice.',
        'A good toupee looks like a good toupee.',
        'A great bulimic consuming engine.',
        'A great deal of intelligence can be invested in ignorance when the need for illusion is deep.',
        "A great leader doesn't treat problems as special. He treats them as normal.",
        "A great product is deep, indulgent, complete and elegant. (Dice)",
        'A guilty conscience needs no accuser',
        'A heart warming confection sunk in platitudes.',
        'A house divided cannot stand.',
        'A household should be of the hill, not on the hill.',
        'A kindness that was also an assertion of power. It was so reassuring to him to be able to use it.',
        'A lack of talent no longer need be a detriment to advancement.',
        'A large brain does not guarantee large intellect.',
        'A large man has difficulty exercising his wits fully.',
        'A leader is a dealer of hope.',
        'A leader is the one who gets followed.',
        'A leader must be a dealer in hope.',
        'A lesson taught with humor is retained.',
        'A liar ought to have a good memory.',
        'A lie can be halfway around the world before the truth gets its boots on.',
        'A lie may fool someone else, but it tells you the truth about yourself.',
        'A lie repeated often enough becomes the truth.',
        'A life crowded with incident.',
        'A life lived in fear is a life half-lived.',
        'A life spent in making mistakes is not only more honorable but more useful than a life spent doing nothing.',
        "A life's ruin of dreams.",
        'A lifetime spent on the border between chutzpah and hubris.',
        "A lighthouse doesn't tell you which way to go, it's just a signal to keep you off the rocks.",
        'A lighthouse provides illumination and warning, but not guidance or direction.',
        'A lion at the gate.',
        'A little beauty is preferable to much wealth.',
        'A little inaccuracy sometimes saves tons of explanation.',
        'A little knowledge is a dangerous thing.',
        'A little sincerity is a dangerous thing, and a great deal of it is absolutely fatal.',
        'A live plow horse is still better than a dead thoroughbred.',
        'A loaded dealer is a loyal dealer.',
        'A longing to wander tears my heart when I hear trees rustling in the wind at evening.',
        "A lot of people try to think up ideas. I'm not one. I'd rather accept the irresistible possibilities of what I can't ignore.",
        'A lot of professionals are crackpots.',
        "A loveless world is a dead world, and always there comes an hour when one is weary of prisons, of one's work, and of devotion to duty, and all one craves for is a loved face, the warmth and wonder of a loving heart.",
        'A magician is an actor impersonating a magician.',
        "A man can't know what it's like to be a mother.",
        'A man difficult to like and impossible not to admire.',
        'A man forever voyaging through strange seas of thought, alone.',
        'A man hears what he wants to hear and disregards the rest.',
        'A man is known by the company he keeps.',
        'A man is never more on trial than in a moment of excessive good fortune.',
        'A man is not finished when he is defeated. He is defeated when he quits.',
        'A man is not old until regrets take the place of dreams.',
        'A man must descend very low to find the force to rise again.',
        'A man who is lucky in his enemies.',
        'A man who knows a subject thoroughly, a man so soaked in it that he eats it, sleeps it and dreams it - this man can always teach it with success, no matter how little he knows of technical pedagogy.',
        'A man who runs after two rabbits may not catch any.',
        'A man who strives after an effect not infrequently achieves it.',
        "A man will be imprisoned in a room with a door that's unlocked and opens inwards as long as it does not occur to him to pull rather than push it.",
        'A man with no soul, no inner convictions, he had the integrity of a hyena and the style of a poison toad.',
        'A man who is quiet and full and closed like a well in a village that has been abandoned by all its inhabitants.',
        'A man without paranoia is a man not in full possession of the facts.',
        "A man's worst enemy can't wish him what he thinks up for himself.",
        'A message often repeated is a message often remembered.',
        'A minor operation is one performed on someone else.',
        'A mistake in the making.',
        'A mistake is a mistake. Another mistake is normal. Only the same mistake twice makes you a fool.',
        "A model (or business plan) doesn't necessarily get you to the truth. Eventually math stalls out and something more human – intuition, experience, wisdom – has to take over.",
        'A mother who is really a mother is never free.',
        'A music publishing company run by deaf people.',
        'A natural is someone who does his homework.',
        "A new idea is delicate. It can be killed by a sneer or a yawn; it can be stabbed to death by a quip and worried to death by a frown on the right man's brow.",
        'A new learning experience from an old familiar friend.',
        'A noble goal, shared, is an incredible source of power.',
        "A nod's as good as a wink to a blind man.",
        'A nuisance may merely be a right thing in the wrong place like a pig in the parlor instead of the barnyard.',
        'A painting should not mean - but be.',
        'A past that was no more important to me personally than money is to a rock.',
        'A perception, once fixed in the public imagination, tends to crowd out the possibility of all others.',
        'A person going nowhere can be sure of reaching his destination.',
        'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.',
        'A picket fence in front of a tidal wave.',
        'A piece of instruction comes quietly but indelibly across….',
        'A place where sorrow and salvation exist in a continuum.',
        "A player's effectiveness is directly related to his ability to be right there, doing that thing, in the moment. All the preparation is no good if it can't be put into action at game time. He must be able to respond in the here and now.",
        'A poet is someone with a genius for lying and an adoration of the truth.',
        "A poor man's roast and a rich man's death are sniffed far off.",
        'A prayer for the wild at heart kept in cages.',
        'A product is not a product unless it sells.',
        'A profession is a personal thing that man acquires. It cannot be inherited. It cannot be bequeathed. Only he who, having made the acquisition, puts to use that knowledge and skill with all his ability and complete dedication of purpose can be truly called a professional. (R.E. Onstad)',
        'A quiet man with a violent mind.',
        'A prophet is not without honor, except in his own country and among his own kin, and in his own house.',
        'A relaxed man is not necessarily a better man.',
        'A romantic comedy has to have characters grow to some kind of realization that the world is bigger than their little concerns.',
        "A screenplay is essentially a selling tool. It isn't always the movie that gets made, but it's always what gets the movie made.",
        'A secret always has a timetable.',
        'A sense of failure is one of the most insistent feelings held by successful people.',
        'A sense of timing is the mark of genius.',
        'A sham necklace of bitter brevities or false, hollow eulogy will not do for criticism.',
        'A ship ought not to be held by one anchor, nor life by a single hope.',
        'A sincere effort is all you can ask.',
        'A sinkhole of depraved venality.',
        'A small bank account focuses the mind.',
        'A software product takes ten times as much effort as a program written for private use.',
        'A story we tell ourselves about what we could have been.',
        'A stream cannot rise above its source.',
        'A strong sense of duty imprisons you.',
        'A stumble may prevent a fall.',
        "A stupid man's report of what a clever man says can never be accurate, because he unconsciously translates what he hears into something he can understand.",
        'A surrealist cage: those inside it are free.',
        "A terrible resentment builds when you've borrowed money and can't pay it back.",
        'A thought to turn the mind to pure Jell-O.',
        "A tree is best measured when it's laid down.",
        'A true friend always stabs you in the front.',
        'A turtle on a fencepost.',
        'A valiant heart always trumps sheer talent.',
        "A verbal agreement isn't worth the paper it's written on.",
        'A vision without the ability to execute is probably a hallucination.',
        'A waist is a terrible thing to mind.',
        'A waste of skin.',
        'A wealth of advice is far less instructive than a strong example.',
        'A well-balanced Irishman - a man with chips on both shoulders.',
        'A wide screen just makes a bad film twice as bad.',
        'A willingness to be held accountable.',
        'A winning performance always beats a winning attitude. Give me action, not motivation.',
        'A wise man will make more opportunities than he finds.',
        'A work of art is good if it has sprung from necessity.',
        'A world of woozy song.',
        'A world shot through with contingency.',
        'A writer is someone for whom writing is more difficult than it is for other people.',
        'Abdicate: give up hope of ever having a flat stomach.',
        'Ability has nothing to do with opportunity.',
        'Ability may get you to the top, but it takes character to keep you there.',
        'Absolute submission can be a form of freedom.',
        'Absolutely nothing great in the world has been accomplished without passion.',
        'Abstraction is a type of decadence.',
        'Abuse of power comes as no surprise.',
        'Accidents happen to people who are inadequately prepared.',
        'Accommodation to parental needs often (but not always) leads to the "as-if personality". This person develops in such a way that he reveals only what is expected of him. He cannot develop and differentiate his true self, because he is unable to live with it.',
        'Accomplishments bring you admiration, not love.',
        'Accumulation of power does not provide security.',
        'Act first to desire your own good opinion of yourself.',
        'Act like a crazy dog, wear sashes and other fine clothes, carry a rattle and dance along the roads singing crazy dog songs after everyone else has gone to bed.',
        'Action causes more trouble than thought.',
        'Action conquers fear.',
        'Action is the antidote to despair.',
        "Activity doesn't necessarily yield achievement.",
        'Actors are alcoholics waiting to happen.',
        'Actors are idols. Heroes are those with something at stake.',
        'Add little to little and there will be a big pile.',
        'Adding manpower to a late software project makes it later.',
        "Adding years to life is science's job; adding life to those additional years is education's task.",
        'Addition by subtraction.',
        'Adventure is something you seek for pleasure or profit – for the illusion of being more alive than ordinarily but experience is what really happens to you in the long run; the truth that finally overtakes you.',
        "Advertising is necessarily a trick, whereas art is not a trick; it's an illusion that tells the truth.",
        "Advertising is like making love to a 500 pound gorilla -- you don't stop when you want to.",
        'Advertising is the plastic surgery of business.',
        'Advertising is the rattling of a stick inside a swill bucket.',
        "Advertising was the dot.com's storefront.",
        'Aesthetics is for the artist as ornithology is for the birds.',
        'After a first true love, you never love like that again in your life.',
        'After learning the tricks of the trade, many of us think we know the trade.',
        'After the ship has sunk, everyone knows how she might have been saved.',
        'After the third call, assume the rumor is true.',
        'After things go from bad to worse, the cycle repeats itself.',
        'After you finish being smart in this business, you also have to be lucky.',
        'Age and treachery will overcome youth and skill. (Triumph Over)',
        'Age cannot wither her.',
        'Age is a very high price to pay for maturity.',
        'Agoraphobia - too much openness.',
        "Ain't but two kinda people in the wurl. The ones that gives and the ones that takes, and know'n what ya gonna be is the difference between bein' a player or suckuh.",
        "All believing is essentially betting – since we cannot know what's right or wrong – we make bets based on experience.",
        'All business success is based on two things: building relationships and patience.',
        'All cats are grey in the dark.',
        'All change is not growth, as all movement is not forward. (Glasgow)',
        'All cruel people describe themselves as paragons of frankness.',
        'All damaged people are dangerous because they have no pity. They know that others can survive, as they did.',
        'All evolution, cultural as well as biological, is a process of continuous adaptation to unforeseen events, to contingent circumstances which could not have been forecast.',
        'All farewells should be sudden.',
        'All great discoveries are founded in small thefts.',
        'All great ideas ultimately degenerate into work.',
        'All great wars are lost in the middle.',
        'All happy families are alike and every unhappy family is unhappy according to its own ways.',
        "All I have to do is finish the game. I'll finish it, maybe not standing up, but I'll finish it.",
        'All life is a game of power.',
        'All living things harbor an impulse to economize, to accomplish more with less.',
        'All my friendships are becoming hardships.',
        'All my possessions for a moment of time.',
        'All of the moves; none of the courage-afraid to throw a punch that might land.',
        'All of these you are',
        '  And each is partly you',
        '  And none of them is false',
        '  And none is wholly true. (Stephen Vincent Benet)',
        'All of this is like tears in the rain.',
        'All our "isms" are "wasms."',
        'All our knowledge has its origins in our perceptions.',
        'All our knowledge is about the past and all our decisions are about the future.',
        'All progress depends on the unreasonable man.',
        'All sorrows can be borne.',
        'All strategies are vulnerable to reality, expected and unexpected.',
        'All that glitters is not gold.',
        'All the blessings we enjoy are the fruits of labor, toil, self-denial and study.',
        "All the drive and ambition in the world is of little use if you're on the wrong road.",
        'All the knowledge I possess anyone else can acquire, but my heart is all my own.',
        'All the passions produce prodigies. A gambler is capable of watching and fasting, almost like a saint.',
        'All the slow rabbits have been caught.',
        'All the thoughts of a turtle are turtle.',
        'All the wood behind one arrowhead. (Focus)',
        'All things being equal, fat people use more soap.',
        'All things come to those who wait.',
        'All things continue until they stop.',
        'All things with a vengeance.',
        "All too often, people believe that creativity leads to innovation. It doesn't.",
        'All wise negotiations mean settling for what you can get right now rather than what you want one day.',
        "All women become like their mothers. That is their tragedy. No man does. That's his.",
        'All work is creative work if done by a thinking mind, and no work is creative if done by someone who repeats in uncritical stupor a routine he has learned from others.',
        'All writers, I think, are to one extent or another damaged. Writing is our way of repairing ourselves. I was filling a hole in myself.',
        'All writing is therapy. To some extent all writers seek their craft to heal a wound in themselves, to make themselves whole.',
        'All you really have that matters are feelings.',
        "Allow children to be happy in their own way, for what better way will they ever find?",
        'Alone we can do so little; together we could do so much.',
        'Almost everything is easier to get into than out of.',
        'Alter your expectations.',
        "Although the wages of sin may be death, it's nice work if you can get it.",
        'Always assume it will take twice as long and be twice as hard as your worst possible dreams.',
        'Always be in a state of becoming.',
        'Always disappointed, never surprised.',
        'Always fight your battles on familiar ground.',
        'Always give wrong directions to a contrarian.',
        "Always go to other people's funerals, otherwise they won't come to yours.",
        'Always have your bags packed.',
        'Always suspect a man who affects great softness of manner, an unruffled evenness of temper, and an enunciation studied, slow and deliberate. These things are all unnatural, and bespeak a degree of mental discipline into which he that has no purpose of craft or design to answer cannot submit to drill himself. The most successful knaves are usually of this description. They affect the innocence of the dove, which they have not, in order to hide the cunning of the serpent, which they have.',
        'Always remember to pillage before you burn.',
        'Always striving, never arriving.',
        "Always take a job that's too big for you.",
        'Always the years together, always the hours.',
        "Always try to see your opponent's cards.",
        'Ambition - ambition to do - ambition to be.',
        'Ambition is exhausting. It makes you friends with people for the wrong reasons, just like drugs.',
        'Ambition is just as dangerous as complacency.',
        'Ambition is one of the more ungovernable passions of the human heart. The love of power is insatiable and uncontrollable.',
        'America is like a melting pot: the people at the bottom get burned and the scum floats to the top.',
        "Americans aren't going to trust a party to defend America if it can't defend itself.",
        'Among the first signs of serious problems is an abandonment of perspective, a feeling that one is unique in his troubles. Everyone has the same problems. The only differences are degree and the richness of the mix.',
        'Amusing, not doubt, yet hardly moving further below the surface than a paper boat in a bath tub and, like the boat, ever in imminent danger of becoming a shapeless, sodden mess.',
        'An administration, like a machine, does not create. It carries on.',
        'An apology not accompanied by change is an insult.',
        'An artist is his own fault.',
        "An artist's work develops out of need, compassion and commitment.",
        'An economist is an expert who will know tomorrow why the things he predicted yesterday did not happen today.',
        "An elephant's tampon.",
        "An elite is inevitable.",
        'An enemy whose mind is distressed is an uncommonly vulnerable enemy.',
        'An era ends when its dreams are exhausted.',
        'An eternity of sweat, tears - and toil.',
        'An expert is someone more than 50 miles from home, who has no responsibility for implementing the advice he gives, and shows slides.',
        'An explanation of cause is not a justification by reason.',
        "An idea isn't responsible for the people who believe it.",
        "An imposer: one about whom one worries whether his response to one's next remark will be a smile or a snarl.",
        "An industry not based on a developmental model (we will get better and better), but on radical obsolescence—what you're doing now will be meaningless tomorrow.",
        'An institution is simply the lengthened shadow of a single individual.',
        'An institution that stands for nothing will fall for anything.',
        'An intellectual in show business is like the smartest bear in the zoo.',
        'An investment in knowledge always pays the best interest.',
        'An invisible presence—like a fume or a scent.',
        'An iron girder in a house of cards.',
        "An oak without wind doesn't grow strong.",
        'An ounce of loyalty is worth a pound of cleverness.',
        'An ounce of momentum is worth a pound of acceleration.',
        "An oxygen-free environment which doesn't support life.",
        'An uncommon amount of common sense.',
        'And how the same inexorable price must still be paid for the same great purchase. (Whitman)',
        'And in the night of death, hope sees a star, and listening to love hears the rustle of a wing.',
        "And it was to this city… that I always knew I must return, for it was the mistress of one's wildest hopes.",
        "And, like a dog at a dinner party, he won't go away.",
        'And so, he slowly, systematically, and hopelessly sat down and shut up.',
        "And the days dwindle down to a precious few – September… November… and these few precious days I'll spend with you.",
        'And the rest, as they say, was mystery.',
        'And the rest, the children, the country kitchen, the domestic bliss, we leave to others, who will have different regrets.',
        'And they, since they were not the ones dead, turned to their affairs.',
        'And think not you can direct the course of love, for love, if it finds you worthy directs your course.',
        'Anytime anyone has an idea, five other people elsewhere have the same idea simultaneously.',
        "And the days dwindle down to a precious few – September…November…and these few precious days I'll spend with you.",
        'And those who are successful,',
        '  Be always on your guard;',
        '  Success walks hand in hand with failure,',
        '  Along Hollywood Boulevard.',
        'And when you have reached the mountain top, then you shall begin to climb.',
        'And when your walls come tumbling down, I will always be around.',
        "Anger is not cathartic, and you won't break a losing streak by exacting revenge on your perceived enemies.",
        'Another victory like this, and we are lost.',
        'Antisocial behavior increases in proportion to the excuses that intellectuals make for it.',
        'Any artist has only one revolution in him.',
        'Any clear way, though it lead to death, is preferable to the tangle of uncertainty.',
        'Any day above ground is a good day.',
        "Any day you're not moving the ball forward, it's moving backwards.",
        'Any event, once it has occurred, can be made to appear inevitable by any competent journalist or historian.',
        'Any excuse will serve a tyrant.',
        "Any group that would gather to hear a politician speak wouldn't know a good speech if they heard one.",
        "Any man who's extremely successful and takes no pleasure in it is a man after my own heart.",
        "Any person hired by a bureaucracy to respond to public complaints has no power to remedy them.",
        "Any problem you can solve with a check isn't a problem, it's an expense.",
        'Any repeated actions contain deep psychological truth.',
        'Any sufficiently advanced technology is indistinguishable from magic.',
        'Any surplus is immoral.',
        'Any worthwhile goal is difficult to accomplish.',
        'Anybody who gets away with something will come back to get away with a little bit more.',
        'Anybody who has survived his childhood has enough information about life to last him the rest of his days.',
        "Anyone can deal with madness - it's reality that's impossible.",
        'Anyone can hold the helm when the sea is calm.',
        'Anyone in an environment that is not preparing him or her for a tougher future should move out fast.',
        'Anyone who angers you conquers you.',
        'Anyone who closes his eyes to the past is blind to the present.',
        'Anyone who stays somewhere for someone else ends up alone.',
        "Anything can happen now that we've slid over the bridge...anything at all.",
        "Anything can happen to anybody at anytime as long as you find something you're devoted to.",
        "Anything that's not a clear winner is a loser - no living dead.",
        'Anything will fit a naked man.',
        'Anything worth doing at all is worth doing to excess.',
        'Anywhere from soon to shortly after the end of life as we know it.',
        "Aquarium story—rocks, stones, gravel, sand, water - can't put the big things in last.",
        "Are there wounds in the past so strong that they'll pull you back no matter what you do?",
        'Are you still important? Not to myself.',
        "Are you tired of living another man's dream?",
        'Ars est celare artem / It is (true) art to conceal art.',
        'Ars longa, vita brevis / Art is long, life is short.',
        'Arsonists masquerading as fireman.',
        'Art, after all, only embellishes truth. It is not truth itself.',
        "Art begets certainties that biography can't confirm.",
        "Art begins in honesty.",
        "Art does not lie down on the bed that is made for it. It runs away as soon as one says its name. It loves to be incognito. Its best moments are when it forgets what it is called.",
        'Art has no other object than to set aside the symbols of practical utility, the generalities that are conventionally and socially accepted, everything in fact which masks reality from us, in order to set us face to face with reality itself.',
        "Art is a boy's name.",
        "Art is a lie that enables us to see the truth.",
        'Art is like grand music, an eternal act of generosity.',
        'Art is not a profession which can be mastered by study.',
        "Art is not an end in itself. It's a means of addressing humanity.",
        'Art is not truth. Art is a lie that helps you understand the truth.',
        'Art is the only way to run away without leaving home.',
        'Art is the signature of civilizations.',
        'Art, like morality, consists of drawing the line somewhere.',
        'Art serves us best precisely at that point where it can shift our sense of what is possible, when we now know more than we knew before, when we feel we have-by some manner of leap- encountered the truth. That, by the logic of art, is always worth the pain.',
        'Art suffers at the hands of reality.',
        'Artificial intelligence is no match for natural stupidity.',
        'As a man thinketh in his heart, so is he.',
        'As a practical matter, he had no past, only a future.',
        'As focused as a bullet in flight.',
        'As always, victory finds a hundred fathers, but defeat is an orphan.',
        'As long as I am unforgiven',
        '  As far as I am pushed away',
        '  As much as life seems less than living',
        '  I still try.',
        "As long as you act as if you're coming from behind, you have a shot at staying ahead.",
        'As much chance as butter against the sun.',
        "As soon as you start thinking about the beginning, it's the end.",
        'As the camel falls to its knees, more knives are drawn.',
        'As the twig is bent, so is the tree inclined.',
        "As they say in poker, if you're in the game 30 minutes and don't know who the patsy is, you're the patsy.",
        "As tho' to breathe were life. (Tennyson)",
        'As useful as cups of air to a dead man.',
        "As we've gotten more open-minded, we've gotten more closed-hearted.",
        'As you make your bed, so you must lie upon it.',
        'Ask not about things which, if made plain to you, may cause you trouble.',
        'Ask questions until you understand the answers.',
        "\"Ask whether you're working off your \"in\" basket or whether the organization is working off your \"out\" basket. If it's the former, you're reacting rather than leading the organization toward its goal.\"",
        'Asking a writer about critics is like asking a lamppost how it feels about dogs.',
        'Asking my husband to help me write a song would be like asking him to salt my food to his taste.',
        'Asses and elbows.',
        "Assume nothin'",
        'Assume nothing and follow up on everything.',
        'At a time when courage counted most, I lived among the bravest of men.',
        'At least her tattoos were all spelled right.',
        'At present we are combating a trend. But this trend will die out, superseded by others, and then the way we are arguing against it will no longer be understood; people will not see why all this needed saying.',
        'At some point, you need a big building in a bad neighborhood.',
        "At some point in his life, he didn't want to feel, he just wanted to be successful.",
        'At the core of true happiness is the wisdom not to ask for too much.',
        'At the end of the day, politics is about the ability to inflict pain.',
        'At the top, life seeks expression through particular individuals.',
        'At times inactivity is preferable to mindless functioning.',
        'Athletes must fail and must fail as early as possible. Because in the beginning, they get by on their talent alone. But with failure comes thought, and greatness needs the combination of talent and mind.',
        'Attention must be paid.',
        'Attitude can change adversities into assets.',
        'Aurora comes to terms with an unrequited love that cannot penetrate the barriers of self-absorption.',
        'Attitude is more important than facts.',
        'Avoid biting when a simple growl will do.',
        'Avoid interruptive thinking.',
        'Avoid the belief that dealing is preferable to working.',
        'Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure or nothing.',
        'Awards are merely badges of mediocrity.',
        'Axe enters the woods: upon seeing it, the trees said, look, the handle is one of us.',
    ],
    'B': [
        'Bacteria are the only culture some people have.',
        'Bad drama reinforces our prejudices. Good drama appeals to the problems both universal and eternal which are insoluble.',
        'Bad intentions can yield good results.',
        'Bad numbers will get you every time.',
        'Bad spirit is more contagious than good spirit.',
        'Bag of wishes.',
        'Banking may well be a career from which no man really recovers.',
        'Baseball is the only place in life where a sacrifice is really appreciated.',
        'Be better than average.',
        "Be careful not to impart your wisdom to a guest whose background you don't know.",
        'Be careful of the toes you step on today; they may be connected to the ass you have to kiss tomorrow.',
        'Be careful who you step on the way up, because you may have to lean on them on the way down.',
        'Be fearful when the world is greedy and be greedy when the world is fearful.',
        'Be here now.',
        'Be light, stinging, insolent and melancholy.',
        'Be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon them. (Sh.12th night, 11, v)',
        'Be reasonable: do it my way.',
        "'Be so good they can't ignore you.",
        "Be sure that, the next time you hear a ringing declaration, no one is beating on your head.",
        "Be very careful what you put into his head. You'll never get it out. [Talking about Henry VIII]",
        'Be very careful what you wish for, you might get it.',
        'Be wary. Do not lose the substance by grasping at the shadows.',
        'Be wary of a man who urges an action in which he himself incurs no risk.',
        'Beating the competition is relatively easy. Beating yourself is a never-ending commitment.',
        'Beauty creates its own rules of conduct.',
        "Beauty is not a passport, it's a visa.",
        'Beauty will not season soup.',
        'Becoming number one is easier than remaining number one.',
        'Before everything else, getting ready is the secret to success.',
        'Before they made me, they broke the mold.',
        'Before you borrow money from a friend, decide which you need more.',
        'Beg forgiveness, not permission.',
        "Beggars can't be choosers.",
        'Begin somewhere; you cannot build a reputation on what you intend to do.',
        'Beginning a war is like opening the door of a dark room. One never knows what is hidden in the darkness.',
        'Behind an able man, there are always other able men.',
        'Behold I show you a mystery; we shall not all sleep, but we shall all be changed.',
        '  (I Corinthians 15:51)',
        "Being a critic is like being a meter maid. All you do is bring pain into people's lives.",
        "Being a producer doesn't necessarily mean that your arm is laced up to your elbow in Crisco.",
        'Being alone is not the same thing as loneliness.',
        'Being alone with yourself is increasingly unpopular.',
        'Being an editor is a mouse training to become a rat.',
        'Being an intellectual creates lots of questions and no answers. You can fill your life up with ideas and still go home lonely. All you really have that really matters are feelings.',
        'Being courageous requires no exceptional qualifications, no magic formula, no special combination of time, place and circumstance. It is an opportunity that sooner or later is presented to us all.',
        'Being good in business is the most fascinating kind of art. (Warhol)',
        'Being kind is more important than being right.',
        "'Being King is great. There's pressure, but no peer group pressure.",
        'Being obsessive is okay. The first time you say "it," there\'s no impact. The fifth time, they\'re skeptical. The twenty-fifth time, they begin to listen a little bit. The sixty-fifth time, they take you seriously.',
        'Being on the tightrope is living. Everything else is waiting.',
        "Being president is like running a cemetery-you've got a lot of people under you and nobody's listening.",
        "'Being rich is having money. Being wealthy is having time.",
        "'Being self-involved and having the arrogance to think that you have something to say and somebody else should pay attention is a necessary component of an artist's life.",
        "Being smart doesn't mean you make all good decisions. It means you learn from your bad ones, and make the best of all of them.",
        "Being unreasonable is good. It's how things change.",
        'Belching is not a constitutional right.',
        'Believe and succeed.',
        'Believe in yourself and believe in your dreams.',
        'Better a friendly refusal than an unwilling promise.',
        'Better a terrible end than terror without end.',
        'Better face a danger once, than always be in fear.',
        'Better far that you should forget and smile than that you should remember and be sad.',
        'Better Nouveau than never.',
        'Between friends there are no debts.',
        'Between kissing and severe biting, there is a whole continuum of inhibited biting, mock biting, playful gnawing and love bites.',
        'Between lovers a little confession is a dangerous thing.',
        'Beware an old man in a hurry.',
        'Beware the fury of a patient man.',
        'Beware the lollipop of mediocrity. Lick it once and you suck forever.',
        'Better to be good than to be original.',
        'Better to lose with a wise man than win with a fool.',
        'Beyond the mountains, more mountains. (Deye morne ginyin morne.)',
        'Big hat, no cattle.',
        "Bigger is not better but it's better than small.",
        'Birds of a feather flock together.',
        'Birds of prey never weep.',
        'Bite off more than you can chew. Then chew it.',
        'Bitterness and cynicism are the unprincipled despair which arises out of thwarted love. Anyone worth anything wrestles with them and wins because he does not want to be limited to intelligence when a situation requires compassion.',
        "Blame nobody / Expect nothing / Do something",
        "Bliss was it in that dawn to be alive, but to be young was very heaven. (Wordsworth)",
        'Block-and-tackle grunt work.',
        'Blood is thicker than water.',
        'Blood will tell.',
        'Boldness becomes rarer, the higher the rank.',
        'Boldness has genius, power and magic in it. Whatever you can do or dream, you can begin it.',
        'Born with the gift of laughter and a sense that the world is mad.',
        'Born with two helpings of brain and a half-helping of heart.',
        'Boxing is just show business with blood.',
        'Boxing is the only jungle where the lions are afraid of the rats.',
        "Brands are like quick-drying cement. When they're young, they're stretchable and pliant, but over time they become more and more associated with a particular thing and harder to stretch.",
        'Brothers from different mothers.',
        'Brightness falls from the air',
        '...Queens have died young and fair.',
        'Broad comedy is not necessarily dumb comedy.',
        'Broken promises tend to rub on you after the adrenaline subsides, especially on nights alone with nothing to think of but regrets.',
        'Build consensus but never slow progress.',
        'Build on resolve and not upon regret.',
        'Bunny Boiler.',
        'Bureaucracy, the rule of no one, has become the modern form of despotism.',
        'Burger bars and fist food.',
        "Business and anarchy don't mix.",
        'Business is as much fun as fist fighting.',
        "Business is not a sport. It's a war.",
        'Businesses are not paid to reform their customers. They are paid to satisfy them.',
        'Businesses planned for service are apt to succeed; businesses planned for profit are apt to fail.',
        'But I did not die in my fiftieth year. There are few who know me now who do not regard that as a tragedy.',
        "But it was like he came along and whispered some dream in everybody's ear, and somehow we all dreamed it.",
        "But that is the way people are. They want talent, which is in itself something out of the ordinary. But when it comes to the other oddities that are always associated with it, and perhaps are essential to it, they will have none of them and refuse them all understanding. (Thomas Mann)",
        "But these promises we make at night, oh that's all they are, unless we fill them with faith and love, they're as empty as the howlin' wind.",
        "But you who are strong and swift, see that you do not limp, deeming it kindness.",
        'Butthole surfers.',
        'By and by.',
        'By seeing the seed of failure in every success, we remain humble;',
        '...By seeing the seed of success in every failure, we remain hopeful.',
        'By the time you make ends meet, they move the ends.',
        'By your own soul learn to live,',
        '...And if man thwart you pay no heed /',
        '...If man hate you have no care /',
        '...Sing your song / Dream your dream,',
        '...Pray your prayer / By your own soul',
        '...Learn to live',
    ],
    'C': [
        "Call no man lucky until he's dead.",
        'Calm is more conducive to creativity than anxiety.',
        'Can you be so open-minded that your brains fall out?',
        'Can you find a little hole for yourself?',
        "Can't tell the salt from the wound.",
        'Care more than others think is wise.',
        '...Risk more than others think safe',
        '...Dream more than others think is practical',
        '...Expect more than others think is possible.',
        'Caring can cost a lot, but not caring always costs more.',
        'Cash and bury.',
        'Cash flow is more important than your mother.',
        'Cash is a fact -- profit is an accounting opinion.',
        'Cause die-hard terrorists to die hard.',
        '"Celebrated, all-points, fuck-up."',
        "Champions aren't made in gyms. Champions have something deep inside them-a desire, a dream, a vision. They have to have last-minute stamina, they have to be a little faster, they have to have the skill and the will. But the will must be stronger than the skill.",
        'Chance favors the prepared mind.',
        "Chance is the fool's word for fate.",
        "Chance remains forever untamable for fate does what it wants to us and to the world around us. The universe is governed by laws that we will never quite fully understand.",
        'Change: you cannot step twice into the same river, for fresh waters are ever flowing in upon you.',
        'Change before you have to.',
        'Change is certain but progress is not.',
        'Change is inevitable, except from a vending machine.',
        'Change is valuable for its own sake, whether or not it turns out to be an improvement.',
        "Change takes place in an instant; it's the resistance to change that takes time to overcome.",
        'Character counts. Family matters.',
        'Character – giving up on perfection without giving up on hope.',
        'Character is destiny.',
        'Character is determined at the point a man is doing what he likes best.',
        'Character is expressed thru loyalty and mutual commitment.',
        'Character is like a tree and reputation like its shadow. The shadow is what we think of it; the tree is the real thing.',
        "Charm isn't a belief. It isn't a guide. It can't tell you where you want to go, it can only help you get there.",
        'Chicken Little only has to be right once.',
        'Children and fools tell the truth.',
        'Children are the hope of the future.',
        'Children are the most cruel of all.',
        "Children with strong fathers learn trust early on, that their needs will be met, that they're wanted…",
        "Children's two fears-being devoured; being abandoned.",
        'Choosing to accept that there are things one does not choose.',
        'Circumstances are the rulers of the weak; they are but the instruments of the wise.',
        '"Citius, altius, fortius" / "Swifter, higher, stronger"',
        'Civilization advances by extending the number of important operations which we can perform without thinking of them.',
        'Class commands rather than demands the respect of others.',
        'Clenched fist-',
        '  1. Communication',
        '  2. Trust',
        '  3. Collective Responsibility',
        '  4. Caring',
        '  5. Pride',
        'Clever people master life; the wise illuminate it and create fresh difficulties.',
        'Cleverness carries the day, but wisdom endures.',
        'Climbing a mountain;',
        '  There are no shortcuts.',
        '  No one can take the steps for you.',
        "  You make it, or you don't.",
        'Climbing is not about conquering the rock; it is about conquering yourself.',
        'Clinging to the past is the problem. Embracing change is the solution.',
        'Clive has the mind of a bank executive and the ears of a teenager.',
        'Close the back door.',
        'Coffee: a person who is coughed upon',
        "Coincidences can be nothing more than God's way of choosing to remain anonymous.",
        'Cold enough to freeze the balls off a brass monkey.',
        "Combat forever distanced him from anyone who hadn't been there.",
        'Come see me when',
        "Comedy is full of boys who didn't go to the prom.",
        'Coming together is a begining.',
        '  Keeping together is progres.',
        '  Working together is success.',
        'Command by instinct is swifter, subtler, deeper, more accurate, more in touch with reality than command by conscious mind.',
        'Commitment gives one the ability to become what he has always dreamed of being.',
        'Commitment is the daily triumph of integrity over skepticism.',
        'Commitment is what transforms a promise into reality.',
        'Commitment, not authority, produces results.',
        'Communication is the solvent for all things.',
        "Companies aren't sold, they are bought.",
        'Companies that are growing quickly and those that are not are different in every imaginable way.',
        'Companies that have a soul – companies that have a clue.',
        'Compete on execution.',
        'Competing pressures tempt one to believe that an issue deferred is a problem avoided; more often it is a crisis invented.',
        'Competition, which though painful, fierce, frequently ruthless, sometimes Darwinian in its pitilessness, is a cornerstone of our highly successful economic system. Competition is not a tort.',
        "Competitive response: even if you lose, you will have learned something. Maybe you'll see the need for more conditioning, or knowing your competition better, or using different tactics.",
        'Competitors: if they were drowning to death, I would put a hose in their mouth.',
        'Complete the circuit.',
        'Complicit in their own mediocrity and indifferent to it.',
        'Compromise is simply when we change the question to fit the answer.',
        'Conan the Librarian-Lots of arbitrary rules and utterly no mercy.',
        'Conceive, believe, achieve.',
        'Concentrate on opportunities, not problems.',
        'Concern for what is right causes us to do our best-knowledge of what is best inspires us to do what is right.',
        'Confidence is the expectation of a positive outcome.',
        'Confusion is a higher state of knowledge than ignorance.',
        "Conqueror sans peril, c'est triompher sans gloire. (To conquer without peril is to triumph without glory.)",
        'Conscience gets a lot of credit that belongs to cold feet.',
        'Consequences are not, alas, inevitably the product of intentions; they are determined by the collisions of intentions and reality.',
        'Consider rejection a lack of imagination on their part.',
        'Consistency is always easier to defend than correctness.',
        'Consistency requires you to be as ignorant today as you were a year ago.',
        'Constitutions, like diets, are meant to restrict us most when temptation is greatest.',
        'Content is king but context is kong.',
        'Contention is better than loneliness.',
        "Contrary to popular belief, everything in life doesn't have a clear-cut solution.",
        'Control the agenda.',
        'Control your destiny, or someone else will.',
        "Control your time – the inbox reflects the priorities of others. Lead, don't react.",
        'Convincing yourself is easy.',
        "Could you really explain to a fish what it's like to walk on land? One day on land is worth a thousand years of talking about it, and one day running a business has exactly the same kind of value.",
        "Count on self-interest, not self-sacrifice, and you'll never be disappointed.",
        'Courage is not how a man stands or falls, but how he gets back up again.',
        'Courage is not the only virtue, but it is the single virtue without which all the other virtues are meaningless.',
        'Courage is not the absence of fear but the ability to carry on with dignity in spite of it.',
        'Courage is not the absence of fear; but rather the judgment decision that something else is more important than fear.',
        'Courage is the first of human qualities, because it is the quality which guarantees all of the others.',
        'Courage is the temporary absence of selfishness.',
        "Courage should always be rewarded-even when it's born of desperation.",
        'Cowards die many times before their death.',
        'Create a dream which your customers can share.',
        "Create tomorrow-don't defend yesterday.",
        '"Creation" has been so overused that even God must be embarrassed to have it attributed to Him.',
        'Creative mess is better than stagnant neatness.',
        'Creative minds have always been known to survive any kind of bad training.',
        'Credentials are not the same as accomplishments.',
        "Critics at their worst/ could never criticize/ the way that you do/ No, there's no one else, I find/ to undermine or dash a hope/ quite like you.",
        "Crooked as a hound's hind leg.",
        'Cruel but fair.',
        'Cry havoc, and let slip the dogs of war. (Marc Anthony)',
        'Culture is a consequence of the way you run your business and your performance.',
        'Customer expectations are progressive.',
        "Customer satisfaction isn't everything-it's the only thing.",
        'Customers vote with dollars, not hugs.',
        'Customers want 1/4" holes, not 1/4" drills.',
        
    ],
    'D': [

        'Damaged goods is all I see. Hardened faces look back at me. Where are all the innocents-unscarred by the battle.',
        'Daring ideas are like chessmen moved forward; they may be beaten, but they may start a winning game.',
        'Darwinian chance rather than providential design determines what happens.',
        '  Data are not facts.',
        '  Facts are not information.',
        '  Information is not knowledge.',
        '  Knowledge is not truth.',
        '  Truth is not wisdom.',
        'Death is afraid of him because he has the heart of a lion.',
        'Decadence is deliberate cruelty.',
        'Decency is a relative thing.',
        'Deception is invariably practiced on the self before others.',
        'Decide on what you think is right, and stick to it.',
        "Deep down, he's very shallow.",
        "Deep pockets don't sue shallow ones.",
        'Deeper analysis does not always lead to keener judgements.',
        'Defeat is worse than death because you have to live with defeat.',
        'Deformed by fantasy-mutilated by reality.',
        'Deja new',
        'Delay only compounds mistakes.',
        'Democracy in meetings is not a value in itself.',
        'Democracy is like blowing your nose. You may not do it well, but you ought to do it yourself.',
        'Denial is an ineffective strategy.',
        "Depression doesn't necessarily kill a person's sense of humor.",
        'Depression is merely anger without enthusiasm.',
        'Description is more valuable than metaphor.',
        'Design is not veneer, it is the fundamental soul of a creation.',
        'Desolation is not the same thing as emptiness, because unlike emptiness, it can fill a space.',
        'Desperation, not vision.',
        'Desperation is the raw material of drastic change. Only those who can leave behind everything they have ever believed in can hope to escape.',
        "Destiny is not a matter of chance, it's a matter of choice. It is not a thing to be waited for, it's a thing to be achieved.",
        'Detail is the difference between ordinary and extraordinary.',
        'Die fast and quiet when they interrogate you or live so long that they are ashamed to hurt you anymore.',
        'Difference between a mishap and a tragedy. If Gladstone fell into the Thames, it would be a mishap. If anyone pulled him out, it would be a tragedy. (Disraeli)',
        'Difference between cheese and chalk.',
        "Different isn't always better, but better is always different.",
        'Difficulties exist to be surmounted.',
        "Dig your well before you're thirsty.",
        'Dijon vu – the same mustard as before.',
        'Diplomacy is the art of letting someone else have your way.',
        'Direct your efforts more to preparing youth for the path and less to preparing the path for youth.',
        'Disasters do not simply occur; they evolve.',
        'Discipline:',
        '  1. Do what has to be done',
        '  2. When it has to be done',
        '  3. As well as it can be done',
        '  4. Do it that way all the time',
        'Discipline is a convenient way of avoiding an adjustment to rapidly changing circumstances.',
        'Discipline is always worthwhile.',
        'Discovery is seeing what everybody else has seen, and thinking what no one else has thought.',
        'Disorganization is a kind of anesthesia.',
        'Distress is soil for growing businesses.',
        'Do a few of the right things well.',
        'Do a few things very well.',
        'Do I have to give up me to be loved by you?',
        'Do it, fix it, learn.',
        'Do it right the first time-do it very right the second time.',
        'Do less better.',
        'Do not become an archivist of facts. Try to penetrate to the secret of their occurrence, persistently search for the laws which govern them.',
        'Do not expect justice where might is right.',
        'Do not feel certain of anything.',
        'Do not forget an old act of kindness because of a recent dispute.',
        'Do not go gentle into that good night/Old age should burn and rave at close of day/Rage, rage against the dying of the light.',
        'Do not go where the path may lead, go instead where there is no path and leave a trail.',
        'Do not insult the mother alligator until you have crossed the river.',
        'Do not keep away from the measure which has no limit, or from the task which has no end.',
        'Do not look where you fell, but where you slipped.',
        'Do not seek to follow in the foot steps of the masters; seek what they sought.',
        'Do not spoil what you have by desiring what you have not; but remember that what you now have was once among the things you only hoped for.',
        'Do not understand me too quickly.',
        "Do not use a hatchet to remove a fly from your friend's forehead.",
        'Do not wait; the time will never be "just right". Start where you stand and work with whatever tools you may have at your command, and better tools will be found as you go along.',
        'Do not wait for the last judgment. It takes place every day.',
        'Do what you can.',
        "Do you believe in all this success? It's like wine. You don't believe in wine. You drink wine.",
        'Do you love life? Then do not squander time. For time is the stuff life is made of.',
        'Do you think you can fart your way out of it?',
        'Does anyone have any questions for my answers?',
        'Dogs move through our culture as a kind of unresolved issue.',
        "Doing business without advertising is like winking at a girl in the dark; you know what you're doing, but no one else does.",
        'Doing the right things instead of doing things right.',
        'Doing well is not enough if you can do better.',
        'Dollar bills are not the same as brain cells.',
        "Don't argue with the truth.",
        "Don't ask questions of fairy tales.",
        "Don't avoid voiding.",
        "Don't be afraid to make mistakes. If you take a fall, it's because you're learning, and that's better than playing it safe. The name of the game is not to be right all the time. The name of the game is to win. There's a big difference.",
        "Don't be afraid to take a big step if one is indicated. You can't cross a chasm in two small jumps.",
        "Don't blame content. If you put a monkey in a car, it's not the car's fault.",
        "Don't confuse bad management with destiny.",
        "Don't confuse the headlines with the trend lines.",
        "Don't cry because it is over, smile because it happened.",
        "Don't deprive yourself of the joy of giving.",
        "Don't develop anything that you don't want to make, and don't make anything that you can't sell.",
        "Don't embarrass the bread.",
        "Don't ever confuse good manners with agreement.",
        "Don't ever darken my toilet paper again.",
        "Don't ever take down a fence until you know why it was put up.",
        "Don't expect empathy from losers.",
        "Don't expect others to listen to your advice and ignore your example.",
        "Don't expect others to take as much interest in you as you do yourself.",
        "Don't feed the troll in blog space.",
        "Don't find fault. Find a remedy.",
        "Don't find fault. Find a solution.",
        "Don't get out of the Trojan Horse before you're inside the castle.",
        "Don't hold the penny so close to your eye that you can't see the dollar behind it.",
        "Don't invest too much in a charismatic leader.",
        "Don't judge people by their relatives.",
        "Don't learn the tricks of the trade. Learn the trade.",
        "Don't let a little dispute injure a great friendship.",
        "Don't live with your mistakes.",
        "Don't look backward unless that's the direction you're headed.",
        "Don't look down, don't look back.",
        "Don't look to me for the answers. All I want you to use me for is approval.",
        "Don't mistake activity for achievement.",
        "Don't mistake bad ideas for bad intentions.",
        "Don't pay attention to the critics—don't even ignore them.",
        "Don't put a period when God put a comma.",
        "Don't say yes until I finish talking.",
        "Don't tell me the good news—it takes care of itself—tell me the bad news.",
        "Don't think of me as a monopoly; think of me as a company that enjoys 100% customer loyalty.",
        "Don't think of me as your boss, but as a friend who's always right.",
        "Don't threaten a child: either punish him or forgive him.",
        "Don't throw away time on useless resentment or try to see who can hold out longest in stubbornness.",
        "Don't try to buy low. That's like trying to catch a knife.",
        "Don't try to do something cheaply that shouldn't be done at all.",
        "Don't try to get to heaven in one night.",
        "Don't try to suck up or even be nice to your intellectual inferiors. They'll only hate you more for it.",
        "Don't use a plan as a major input to the decision-making process. Use it mainly to recognize change as it takes place.",
        "Don't watch the underclass. It's more likely that the warlords will kill you.",
        'Drama often obscures the real issues.',
        'Dramatic change often comes as a response to imminent collapse.',
        'Dreams with deadlines.',
        'Dress like a bourgeois; think like a revolutionary.',
        'Drinking water from a fire hose.',
        'Drinking your own bath water.',
        "Drive fast. You're harder to hit.",
        'Dumb as a sack of hammers.',
        'DWIM: Do What I Mean.',
        
    ],
    'E': [
        
    ],
    'F': [
        
    ],
    'G': [
        
    ],
    'H': [
        
    ],
    'I': [
        
    ],
    'J': [
        
    ],
    'K': [
        
    ],
    'L': [
        
    ],
    'M': [
        
    ],
    'N': [
        
    ],
    'O': [
        
    ],
    'P': [
        
    ],
    'Q': [
        
    ],
    'R': [
        
    ],
    'S': [
        
    ],
    'T': [
        
    ],
    'U': [
        
    ],
    'V': [
        
    ],
    // Continue for other letters as needed
};

// Variables to handle pagination and search
let currentPage = 1;
let quotesPerPage = 100;
let currentQuotes = [];

// Function to display quotes based on the selected letter
function showQuotes(letter) {
    // Hide the intro section and show the quotes section
    document.getElementById('intro-section').style.display = 'none';
    document.getElementById('quotes-section').style.display = 'block';

    // Set the quotes for the selected letter
    currentQuotes = quotes[letter] || [];
    currentPage = 1; // Reset to the first page
    displayPaginatedQuotes();
}

// Function to display the quotes for the current page
function displayPaginatedQuotes() {
    const quotesList = document.getElementById('quotes-list');
    quotesList.innerHTML = ''; // Clear existing quotes

    // Get the quotes for the current page
    const startIndex = (currentPage - 1) * quotesPerPage;
    const endIndex = Math.min(startIndex + quotesPerPage, currentQuotes.length);
    const paginatedQuotes = currentQuotes.slice(startIndex, endIndex);

    // Display the paginated quotes
    paginatedQuotes.forEach((quote) => {
        const li = document.createElement('li');
        li.textContent = quote;
        quotesList.appendChild(li);
    });

    // Update pagination controls
    updatePaginationControls();
}

// Function to create and display pagination controls
function updatePaginationControls() {
    const paginationControls = document.getElementById('pagination-controls');
    paginationControls.innerHTML = ''; // Clear existing controls

    const totalPages = Math.ceil(currentQuotes.length / quotesPerPage);

    console.log('Total Pages:', totalPages); // Debugging line

    // Only show pagination if more than one page exists
    if (totalPages > 1) {
        for (let i = 1; i <= totalPages; i++) {
            const button = document.createElement('button');
            button.textContent = i;
            if (i === currentPage) {
                button.classList.add('active');  // Only add 'active' class for the current page
            }
            button.addEventListener('click', () => {
                currentPage = i;
                displayPaginatedQuotes();
            });
            paginationControls.appendChild(button);
        }
    }
}


// Function to filter quotes based on a search term
function searchQuotes() {
    const searchTerm = document.getElementById('search-input').value.toLowerCase();
    
    // Filter current quotes by search term
    const filteredQuotes = currentQuotes.filter(quote => 
        quote.toLowerCase().includes(searchTerm)
    );
    
    // Update quotes list based on the search result
    displayFilteredQuotes(filteredQuotes);
}

// Function to display filtered quotes
function displayFilteredQuotes(filteredQuotes) {
    const quotesList = document.getElementById('quotes-list');
    quotesList.innerHTML = ''; // Clear existing quotes

    if (filteredQuotes.length > 0) {
        filteredQuotes.forEach((quote) => {
            const li = document.createElement('li');
            li.textContent = quote;
            quotesList.appendChild(li);
        });
    } else {
        // If no quotes match the search term
        const li = document.createElement('li');
        li.textContent = 'No quotes found.';
        quotesList.appendChild(li);
    }

    // Hide pagination controls when search is active
    document.getElementById('pagination-controls').style.display = 'none';
}

// Initialize the default state when the page loads
function init() {
    // Show the introduction section and hide the quotes section initially
    document.getElementById('intro-section').style.display = 'block';
    document.getElementById('quotes-section').style.display = 'none';
}
