// Quotes data (replace this with your actual quotes data)
const quotes = {
    'A': [
        'A ballet of the obvious',
        'A beautiful theory killed by some ugly little facts.',
        'A bird teaches a fish to swim, without hatred, without bitterness.',
        'A bond of common laughter.',
        'A bore: someone who deprives you of solitude without providing you with companionship.',
        'A bowling alley with lipstick.',
        'A briefcase with a mouth.',
        'A bull who carries his china closet with him.',
        'A candle loses nothing by lighting another candle.',
        'A career is about taking risks.',
        'A certain sunny shamelessness.',
        'A chain is no stronger than its weakest link.',
        'A champion hates to lose even more than he loves to win.',
        "A change of place changes one's luck.",
        'A child does not despise the bubble because it burst; he immediately sets to work to blow another one.',
        'A child should never have to wonder if his parents love him.',
        'A clarity of vision prompted by the purest form of greed.',
        'A committee is a dark alley down which ideas are led to be strangled.',
        'A company is stronger if it is bound by love rather than fear.',
        "A company is the combined rhythms of intelligent people rather than any one person's particular expertise or brains.",
        'A competitive world has two possibilities for you. You can lose. Or, if you want to win, you can change.',
        'A complicity of needy souls.',
        'A computer does not substitute for judgment any more than a pencil substitutes for literacy. But writing without a pencil is no particular advantage.',
        'A confusion of the real with the ideal never goes unpunished.',
        'A constant battle between sharks and suits.',
        'A continual circulation of lies among those who are not much in the way of hearing them contradicted will in time pass for the truth. (Jefferson)',
        'A corporate culture has to be built on expectations of performance, not rules of behavior.',
        "A critic is a man who knows the way, but can't drive the car.",
        'A crowd is not company.',
        'A culture hollowed out by the imperatives of modern life.',
        'A culture of worthless admirations – unjust praise without purpose or end.',
        'A customer is anyone who can tell you "no".',
        "A cynic is a passionate person who doesn't want to be disappointed again.",
        'A dancing nation, fickle and untrue; have oft undone themselves and others too.',
        'A danger foreseen is half avoided.',
        'A dangerously honest man.',
        'A desk is a dangerous place from which to watch your business.',
        'A devaluation is like wetting your pants. It only feels good for a little while.',
        'A diamond is a chunk of coal that made good under pressure.',
        'A diplomat is a man who thinks twice before he says nothing.',
        "A divorce is like an amputation; you survive, but there's less of you.",
        'A doer in a world of doubters.',
        'A doubtful friend is worse than a certain enemy. Let a man be one or the other, and then we know how to meet him.',
        'A dream is a wish your heart makes.',
        "A driving ambition is of little use if you're on the wrong road.",
        "A drowning man will clutch at a straw.",
        "A drunk keeps no secrets.",
        'A failure is not always a mistake. It may simply be the best one can do under the circumstances. The real mistake is to stop trying.',
        'A few things are important; most are not.',
        'A firm is never static - it is either growing or stagnating.',
        "A fish wouldn't get in trouble if it kept its mouth shut.",
        'A fool and his money are soon parted.',
        'A fool is his own informer.',
        'A fool will lose tomorrow reaching back for yesterday.',
        'A fool throws a stone in a pond and ten sages knock themselves out trying to find it.',
        'A friend has the responsibility to be a witness.',
        'A funeral in the brain.',
        'A general may be sincere, if it serves his purpose, but his purpose is never sincerity.',
        'A goal is a dream with a deadline.',
        'A goal without a plan is just a daydream.',
        'A good action appears inevitable in retrospect.',
        "A good day ain't got no rain. A bad day is when I lie in bed and think of what might have been.",
        'A good deed never goes unpunished.',
        'A good hat can make the difference between a bimbo and a princess.',
        'A good idea and some hard work can make a difference.',
        'A good leader knows himself and his times.',
        'A good leader never blames his people for his failings.',
        'A good plan, violently executed right now, is a lot better than a perfect plan executed next week.',
        'A good scare is worth more to a man than good advice.',
        'A good toupee looks like a good toupee.',
        'A great bulimic consuming engine.',
        'A great deal of intelligence can be invested in ignorance when the need for illusion is deep.',
        "A great leader doesn't treat problems as special. He treats them as normal.",
        "A great product is deep, indulgent, complete and elegant. (Dice)",
        'A guilty conscience needs no accuser',
        'A heart warming confection sunk in platitudes.',
        'A house divided cannot stand.',
        'A household should be of the hill, not on the hill.',
        'A kindness that was also an assertion of power. It was so reassuring to him to be able to use it.',
        'A lack of talent no longer need be a detriment to advancement.',
        'A large brain does not guarantee large intellect.',
        'A large man has difficulty exercising his wits fully.',
        'A leader is a dealer of hope.',
        'A leader is the one who gets followed.',
        'A leader must be a dealer in hope.',
        'A lesson taught with humor is retained.',
        'A liar ought to have a good memory.',
        'A lie can be halfway around the world before the truth gets its boots on.',
        'A lie may fool someone else, but it tells you the truth about yourself.',
        'A lie repeated often enough becomes the truth.',
        'A life crowded with incident.',
        'A life lived in fear is a life half-lived.',
        'A life spent in making mistakes is not only more honorable but more useful than a life spent doing nothing.',
        "A life's ruin of dreams.",
        'A lifetime spent on the border between chutzpah and hubris.',
        "A lighthouse doesn't tell you which way to go, it's just a signal to keep you off the rocks.",
        'A lighthouse provides illumination and warning, but not guidance or direction.',
        'A lion at the gate.',
        'A little beauty is preferable to much wealth.',
        'A little inaccuracy sometimes saves tons of explanation.',
        'A little knowledge is a dangerous thing.',
        'A little sincerity is a dangerous thing, and a great deal of it is absolutely fatal.',
        'A live plow horse is still better than a dead thoroughbred.',
        'A loaded dealer is a loyal dealer.',
        'A longing to wander tears my heart when I hear trees rustling in the wind at evening.',
        "A lot of people try to think up ideas. I'm not one. I'd rather accept the irresistible possibilities of what I can't ignore.",
        'A lot of professionals are crackpots.',
        "A loveless world is a dead world, and always there comes an hour when one is weary of prisons, of one's work, and of devotion to duty, and all one craves for is a loved face, the warmth and wonder of a loving heart.",
        'A magician is an actor impersonating a magician.',
        "A man can't know what it's like to be a mother.",
        'A man difficult to like and impossible not to admire.',
        'A man forever voyaging through strange seas of thought, alone.',
        'A man hears what he wants to hear and disregards the rest.',
        'A man is known by the company he keeps.',
        'A man is never more on trial than in a moment of excessive good fortune.',
        'A man is not finished when he is defeated. He is defeated when he quits.',
        'A man is not old until regrets take the place of dreams.',
        'A man must descend very low to find the force to rise again.',
        'A man who is lucky in his enemies.',
        'A man who knows a subject thoroughly, a man so soaked in it that he eats it, sleeps it and dreams it - this man can always teach it with success, no matter how little he knows of technical pedagogy.',
        'A man who runs after two rabbits may not catch any.',
        'A man who strives after an effect not infrequently achieves it.',
        "A man will be imprisoned in a room with a door that's unlocked and opens inwards as long as it does not occur to him to pull rather than push it.",
        'A man with no soul, no inner convictions, he had the integrity of a hyena and the style of a poison toad.',
        'A man who is quiet and full and closed like a well in a village that has been abandoned by all its inhabitants.',
        'A man without paranoia is a man not in full possession of the facts.',
        "A man's worst enemy can't wish him what he thinks up for himself.",
        'A message often repeated is a message often remembered.',
        'A minor operation is one performed on someone else.',
        'A mistake in the making.',
        'A mistake is a mistake. Another mistake is normal. Only the same mistake twice makes you a fool.',
        "A model (or business plan) doesn't necessarily get you to the truth. Eventually math stalls out and something more human – intuition, experience, wisdom – has to take over.",
        'A mother who is really a mother is never free.',
        'A music publishing company run by deaf people.',
        'A natural is someone who does his homework.',
        "A new idea is delicate. It can be killed by a sneer or a yawn; it can be stabbed to death by a quip and worried to death by a frown on the right man's brow.",
        'A new learning experience from an old familiar friend.',
        'A noble goal, shared, is an incredible source of power.',
        "A nod's as good as a wink to a blind man.",
        'A nuisance may merely be a right thing in the wrong place like a pig in the parlor instead of the barnyard.',
        'A painting should not mean - but be.',
        'A past that was no more important to me personally than money is to a rock.',
        'A perception, once fixed in the public imagination, tends to crowd out the possibility of all others.',
        'A person going nowhere can be sure of reaching his destination.',
        'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.',
        'A picket fence in front of a tidal wave.',
        'A piece of instruction comes quietly but indelibly across….',
        'A place where sorrow and salvation exist in a continuum.',
        "A player's effectiveness is directly related to his ability to be right there, doing that thing, in the moment. All the preparation is no good if it can't be put into action at game time. He must be able to respond in the here and now.",
        'A poet is someone with a genius for lying and an adoration of the truth.',
        "A poor man's roast and a rich man's death are sniffed far off.",
        'A prayer for the wild at heart kept in cages.',
        'A product is not a product unless it sells.',
        'A profession is a personal thing that man acquires. It cannot be inherited. It cannot be bequeathed. Only he who, having made the acquisition, puts to use that knowledge and skill with all his ability and complete dedication of purpose can be truly called a professional. (R.E. Onstad)',
        'A quiet man with a violent mind.',
        'A prophet is not without honor, except in his own country and among his own kin, and in his own house.',
        'A relaxed man is not necessarily a better man.',
        'A romantic comedy has to have characters grow to some kind of realization that the world is bigger than their little concerns.',
        "A screenplay is essentially a selling tool. It isn't always the movie that gets made, but it's always what gets the movie made.",
        'A secret always has a timetable.',
        'A sense of failure is one of the most insistent feelings held by successful people.',
        'A sense of timing is the mark of genius.',
        'A sham necklace of bitter brevities or false, hollow eulogy will not do for criticism.',
        'A ship ought not to be held by one anchor, nor life by a single hope.',
        'A sincere effort is all you can ask.',
        'A sinkhole of depraved venality.',
        'A small bank account focuses the mind.',
        'A software product takes ten times as much effort as a program written for private use.',
        'A story we tell ourselves about what we could have been.',
        'A stream cannot rise above its source.',
        'A strong sense of duty imprisons you.',
        'A stumble may prevent a fall.',
        "A stupid man's report of what a clever man says can never be accurate, because he unconsciously translates what he hears into something he can understand.",
        'A surrealist cage: those inside it are free.',
        "A terrible resentment builds when you've borrowed money and can't pay it back.",
        'A thought to turn the mind to pure Jell-O.',
        "A tree is best measured when it's laid down.",
        'A true friend always stabs you in the front.',
        'A turtle on a fencepost.',
        'A valiant heart always trumps sheer talent.',
        "A verbal agreement isn't worth the paper it's written on.",
        'A vision without the ability to execute is probably a hallucination.',
        'A waist is a terrible thing to mind.',
        'A waste of skin.',
        'A wealth of advice is far less instructive than a strong example.',
        'A well-balanced Irishman - a man with chips on both shoulders.',
        'A wide screen just makes a bad film twice as bad.',
        'A willingness to be held accountable.',
        'A winning performance always beats a winning attitude. Give me action, not motivation.',
        'A wise man will make more opportunities than he finds.',
        'A work of art is good if it has sprung from necessity.',
        'A world of woozy song.',
        'A world shot through with contingency.',
        'A writer is someone for whom writing is more difficult than it is for other people.',
        'Abdicate: give up hope of ever having a flat stomach.',
        'Ability has nothing to do with opportunity.',
        'Ability may get you to the top, but it takes character to keep you there.',
        'Absolute submission can be a form of freedom.',
        'Absolutely nothing great in the world has been accomplished without passion.',
        'Abstraction is a type of decadence.',
        'Abuse of power comes as no surprise.',
        'Accidents happen to people who are inadequately prepared.',
        'Accommodation to parental needs often (but not always) leads to the "as-if personality". This person develops in such a way that he reveals only what is expected of him. He cannot develop and differentiate his true self, because he is unable to live with it.',
        'Accomplishments bring you admiration, not love.',
        'Accumulation of power does not provide security.',
        'Act first to desire your own good opinion of yourself.',
        'Act like a crazy dog, wear sashes and other fine clothes, carry a rattle and dance along the roads singing crazy dog songs after everyone else has gone to bed.',
        'Action causes more trouble than thought.',
        'Action conquers fear.',
        'Action is the antidote to despair.',
        "Activity doesn't necessarily yield achievement.",
        'Actors are alcoholics waiting to happen.',
        'Actors are idols. Heroes are those with something at stake.',
        'Add little to little and there will be a big pile.',
        'Adding manpower to a late software project makes it later.',
        "Adding years to life is science's job; adding life to those additional years is education's task.",
        'Addition by subtraction.',
        'Adventure is something you seek for pleasure or profit – for the illusion of being more alive than ordinarily but experience is what really happens to you in the long run; the truth that finally overtakes you.',
        "Advertising is necessarily a trick, whereas art is not a trick; it's an illusion that tells the truth.",
        "Advertising is like making love to a 500 pound gorilla -- you don't stop when you want to.",
        'Advertising is the plastic surgery of business.',
        'Advertising is the rattling of a stick inside a swill bucket.',
        "Advertising was the dot.com's storefront.",
        'Aesthetics is for the artist as ornithology is for the birds.',
        'After a first true love, you never love like that again in your life.',
        'After learning the tricks of the trade, many of us think we know the trade.',
        'After the ship has sunk, everyone knows how she might have been saved.',
        'After the third call, assume the rumor is true.',
        'After things go from bad to worse, the cycle repeats itself.',
        'After you finish being smart in this business, you also have to be lucky.',
        'Age and treachery will overcome youth and skill. (Triumph Over)',
        'Age cannot wither her.',
        'Age is a very high price to pay for maturity.',
        'Agoraphobia - too much openness.',
        "Ain't but two kinda people in the wurl. The ones that gives and the ones that takes, and know'n what ya gonna be is the difference between bein' a player or suckuh.",
        "All believing is essentially betting – since we cannot know what's right or wrong – we make bets based on experience.",
        'All business success is based on two things: building relationships and patience.',
        'All cats are grey in the dark.',
        'All change is not growth, as all movement is not forward. (Glasgow)',
        'All cruel people describe themselves as paragons of frankness.',
        'All damaged people are dangerous because they have no pity. They know that others can survive, as they did.',
        'All evolution, cultural as well as biological, is a process of continuous adaptation to unforeseen events, to contingent circumstances which could not have been forecast.',
        'All farewells should be sudden.',
        'All great discoveries are founded in small thefts.',
        'All great ideas ultimately degenerate into work.',
        'All great wars are lost in the middle.',
        'All happy families are alike and every unhappy family is unhappy according to its own ways.',
        "All I have to do is finish the game. I'll finish it, maybe not standing up, but I'll finish it.",
        'All life is a game of power.',
        'All living things harbor an impulse to economize, to accomplish more with less.',
        'All my friendships are becoming hardships.',
        'All my possessions for a moment of time.',
        'All of the moves; none of the courage-afraid to throw a punch that might land.',
        'All of these you are',
        '  And each is partly you',
        '  And none of them is false',
        '  And none is wholly true. (Stephen Vincent Benet)',
        'All of this is like tears in the rain.',
        'All our "isms" are "wasms."',
        'All our knowledge has its origins in our perceptions.',
        'All our knowledge is about the past and all our decisions are about the future.',
        'All progress depends on the unreasonable man.',
        'All sorrows can be borne.',
        'All strategies are vulnerable to reality, expected and unexpected.',
        'All that glitters is not gold.',
        'All the blessings we enjoy are the fruits of labor, toil, self-denial and study.',
        "All the drive and ambition in the world is of little use if you're on the wrong road.",
        'All the knowledge I possess anyone else can acquire, but my heart is all my own.',
        'All the passions produce prodigies. A gambler is capable of watching and fasting, almost like a saint.',
        'All the slow rabbits have been caught.',
        'All the thoughts of a turtle are turtle.',
        'All the wood behind one arrowhead. (Focus)',
        'All things being equal, fat people use more soap.',
        'All things come to those who wait.',
        'All things continue until they stop.',
        'All things with a vengeance.',
        "All too often, people believe that creativity leads to innovation. It doesn't.",
        'All wise negotiations mean settling for what you can get right now rather than what you want one day.',
        "All women become like their mothers. That is their tragedy. No man does. That's his.",
        'All work is creative work if done by a thinking mind, and no work is creative if done by someone who repeats in uncritical stupor a routine he has learned from others.',
        'All writers, I think, are to one extent or another damaged. Writing is our way of repairing ourselves. I was filling a hole in myself.',
        'All writing is therapy. To some extent all writers seek their craft to heal a wound in themselves, to make themselves whole.',
        'All you really have that matters are feelings.',
        "Allow children to be happy in their own way, for what better way will they ever find?",
        'Alone we can do so little; together we could do so much.',
        'Almost everything is easier to get into than out of.',
        'Alter your expectations.',
        "Although the wages of sin may be death, it's nice work if you can get it.",
        'Always assume it will take twice as long and be twice as hard as your worst possible dreams.',
        'Always be in a state of becoming.',
        'Always disappointed, never surprised.',
        'Always fight your battles on familiar ground.',
        'Always give wrong directions to a contrarian.',
        "Always go to other people's funerals, otherwise they won't come to yours.",
        'Always have your bags packed.',
        'Always suspect a man who affects great softness of manner, an unruffled evenness of temper, and an enunciation studied, slow and deliberate. These things are all unnatural, and bespeak a degree of mental discipline into which he that has no purpose of craft or design to answer cannot submit to drill himself. The most successful knaves are usually of this description. They affect the innocence of the dove, which they have not, in order to hide the cunning of the serpent, which they have.',
        'Always remember to pillage before you burn.',
        'Always striving, never arriving.',
        "Always take a job that's too big for you.",
        'Always the years together, always the hours.',
        "Always try to see your opponent's cards.",
        'Ambition - ambition to do - ambition to be.',
        'Ambition is exhausting. It makes you friends with people for the wrong reasons, just like drugs.',
        'Ambition is just as dangerous as complacency.',
        'Ambition is one of the more ungovernable passions of the human heart. The love of power is insatiable and uncontrollable.',
        'America is like a melting pot: the people at the bottom get burned and the scum floats to the top.',
        "Americans aren't going to trust a party to defend America if it can't defend itself.",
        'Among the first signs of serious problems is an abandonment of perspective, a feeling that one is unique in his troubles. Everyone has the same problems. The only differences are degree and the richness of the mix.',
        'Amusing, not doubt, yet hardly moving further below the surface than a paper boat in a bath tub and, like the boat, ever in imminent danger of becoming a shapeless, sodden mess.',
        'An administration, like a machine, does not create. It carries on.',
        'An apology not accompanied by change is an insult.',
        'An artist is his own fault.',
        "An artist's work develops out of need, compassion and commitment.",
        'An economist is an expert who will know tomorrow why the things he predicted yesterday did not happen today.',
        "An elephant's tampon.",
        "An elite is inevitable.",
        'An enemy whose mind is distressed is an uncommonly vulnerable enemy.',
        'An era ends when its dreams are exhausted.',
        'An eternity of sweat, tears - and toil.',
        'An expert is someone more than 50 miles from home, who has no responsibility for implementing the advice he gives, and shows slides.',
        'An explanation of cause is not a justification by reason.',
        "An idea isn't responsible for the people who believe it.",
        "An imposer: one about whom one worries whether his response to one's next remark will be a smile or a snarl.",
        "An industry not based on a developmental model (we will get better and better), but on radical obsolescence—what you're doing now will be meaningless tomorrow.",
        'An institution is simply the lengthened shadow of a single individual.',
        'An institution that stands for nothing will fall for anything.',
        'An intellectual in show business is like the smartest bear in the zoo.',
        'An investment in knowledge always pays the best interest.',
        'An invisible presence—like a fume or a scent.',
        'An iron girder in a house of cards.',
        "An oak without wind doesn't grow strong.",
        'An ounce of loyalty is worth a pound of cleverness.',
        'An ounce of momentum is worth a pound of acceleration.',
        "An oxygen-free environment which doesn't support life.",
        'An uncommon amount of common sense.',
        'And how the same inexorable price must still be paid for the same great purchase. (Whitman)',
        'And in the night of death, hope sees a star, and listening to love hears the rustle of a wing.',
        "And it was to this city… that I always knew I must return, for it was the mistress of one's wildest hopes.",
        "And, like a dog at a dinner party, he won't go away.",
        'And so, he slowly, systematically, and hopelessly sat down and shut up.',
        "And the days dwindle down to a precious few – September… November… and these few precious days I'll spend with you.",
        'And the rest, as they say, was mystery.',
        'And the rest, the children, the country kitchen, the domestic bliss, we leave to others, who will have different regrets.',
        'And they, since they were not the ones dead, turned to their affairs.',
        'And think not you can direct the course of love, for love, if it finds you worthy directs your course.',
        'Anytime anyone has an idea, five other people elsewhere have the same idea simultaneously.',
        "And the days dwindle down to a precious few – September…November…and these few precious days I'll spend with you.",
        'And those who are successful,',
        '  Be always on your guard;',
        '  Success walks hand in hand with failure,',
        '  Along Hollywood Boulevard.',
        'And when you have reached the mountain top, then you shall begin to climb.',
        'And when your walls come tumbling down, I will always be around.',
        "Anger is not cathartic, and you won't break a losing streak by exacting revenge on your perceived enemies.",
        'Another victory like this, and we are lost.',
        'Antisocial behavior increases in proportion to the excuses that intellectuals make for it.',
        'Any artist has only one revolution in him.',
        'Any clear way, though it lead to death, is preferable to the tangle of uncertainty.',
        'Any day above ground is a good day.',
        "Any day you're not moving the ball forward, it's moving backwards.",
        'Any event, once it has occurred, can be made to appear inevitable by any competent journalist or historian.',
        'Any excuse will serve a tyrant.',
        "Any group that would gather to hear a politician speak wouldn't know a good speech if they heard one.",
        "Any man who's extremely successful and takes no pleasure in it is a man after my own heart.",
        "Any person hired by a bureaucracy to respond to public complaints has no power to remedy them.",
        "Any problem you can solve with a check isn't a problem, it's an expense.",
        'Any repeated actions contain deep psychological truth.',
        'Any sufficiently advanced technology is indistinguishable from magic.',
        'Any surplus is immoral.',
        'Any worthwhile goal is difficult to accomplish.',
        'Anybody who gets away with something will come back to get away with a little bit more.',
        'Anybody who has survived his childhood has enough information about life to last him the rest of his days.',
        "Anyone can deal with madness - it's reality that's impossible.",
        'Anyone can hold the helm when the sea is calm.',
        'Anyone in an environment that is not preparing him or her for a tougher future should move out fast.',
        'Anyone who angers you conquers you.',
        'Anyone who closes his eyes to the past is blind to the present.',
        'Anyone who stays somewhere for someone else ends up alone.',
        "Anything can happen now that we've slid over the bridge...anything at all.",
        "Anything can happen to anybody at anytime as long as you find something you're devoted to.",
        "Anything that's not a clear winner is a loser - no living dead.",
        'Anything will fit a naked man.',
        'Anything worth doing at all is worth doing to excess.',
        'Anywhere from soon to shortly after the end of life as we know it.',
        "Aquarium story—rocks, stones, gravel, sand, water - can't put the big things in last.",
        "Are there wounds in the past so strong that they'll pull you back no matter what you do?",
        'Are you still important? Not to myself.',
        "Are you tired of living another man's dream?",
        'Ars est celare artem / It is (true) art to conceal art.',
        'Ars longa, vita brevis / Art is long, life is short.',
        'Arsonists masquerading as fireman.',
        'Art, after all, only embellishes truth. It is not truth itself.',
        "Art begets certainties that biography can't confirm.",
        "Art begins in honesty.",
        "Art does not lie down on the bed that is made for it. It runs away as soon as one says its name. It loves to be incognito. Its best moments are when it forgets what it is called.",
        'Art has no other object than to set aside the symbols of practical utility, the generalities that are conventionally and socially accepted, everything in fact which masks reality from us, in order to set us face to face with reality itself.',
        "Art is a boy's name.",
        "Art is a lie that enables us to see the truth.",
        'Art is like grand music, an eternal act of generosity.',
        'Art is not a profession which can be mastered by study.',
        "Art is not an end in itself. It's a means of addressing humanity.",
        'Art is not truth. Art is a lie that helps you understand the truth.',
        'Art is the only way to run away without leaving home.',
        'Art is the signature of civilizations.',
        'Art, like morality, consists of drawing the line somewhere.',
        'Art serves us best precisely at that point where it can shift our sense of what is possible, when we now know more than we knew before, when we feel we have-by some manner of leap- encountered the truth. That, by the logic of art, is always worth the pain.',
        'Art suffers at the hands of reality.',
        'Artificial intelligence is no match for natural stupidity.',
        'As a man thinketh in his heart, so is he.',
        'As a practical matter, he had no past, only a future.',
        'As focused as a bullet in flight.',
        'As always, victory finds a hundred fathers, but defeat is an orphan.',
        'As long as I am unforgiven',
        '  As far as I am pushed away',
        '  As much as life seems less than living',
        '  I still try.',
        "As long as you act as if you're coming from behind, you have a shot at staying ahead.",
        'As much chance as butter against the sun.',
        "As soon as you start thinking about the beginning, it's the end.",
        'As the camel falls to its knees, more knives are drawn.',
        'As the twig is bent, so is the tree inclined.',
        "As they say in poker, if you're in the game 30 minutes and don't know who the patsy is, you're the patsy.",
        "As tho' to breathe were life. (Tennyson)",
        'As useful as cups of air to a dead man.',
        "As we've gotten more open-minded, we've gotten more closed-hearted.",
        'As you make your bed, so you must lie upon it.',
        'Ask not about things which, if made plain to you, may cause you trouble.',
        'Ask questions until you understand the answers.',
        "\"Ask whether you're working off your \"in\" basket or whether the organization is working off your \"out\" basket. If it's the former, you're reacting rather than leading the organization toward its goal.\"",
        'Asking a writer about critics is like asking a lamppost how it feels about dogs.',
        'Asking my husband to help me write a song would be like asking him to salt my food to his taste.',
        'Asses and elbows.',
        "Assume nothin'",
        'Assume nothing and follow up on everything.',
        'At a time when courage counted most, I lived among the bravest of men.',
        'At least her tattoos were all spelled right.',
        'At present we are combating a trend. But this trend will die out, superseded by others, and then the way we are arguing against it will no longer be understood; people will not see why all this needed saying.',
        'At some point, you need a big building in a bad neighborhood.',
        "At some point in his life, he didn't want to feel, he just wanted to be successful.",
        'At the core of true happiness is the wisdom not to ask for too much.',
        'At the end of the day, politics is about the ability to inflict pain.',
        'At the top, life seeks expression through particular individuals.',
        'At times inactivity is preferable to mindless functioning.',
        'Athletes must fail and must fail as early as possible. Because in the beginning, they get by on their talent alone. But with failure comes thought, and greatness needs the combination of talent and mind.',
        'Attention must be paid.',
        'Attitude can change adversities into assets.',
        'Aurora comes to terms with an unrequited love that cannot penetrate the barriers of self-absorption.',
        'Attitude is more important than facts.',
        'Avoid biting when a simple growl will do.',
        'Avoid interruptive thinking.',
        'Avoid the belief that dealing is preferable to working.',
        'Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure or nothing.',
        'Awards are merely badges of mediocrity.',
        'Axe enters the woods: upon seeing it, the trees said, look, the handle is one of us.',
    ],
    'B': [
        'Believe in yourself.',
        'Be the change you wish to see.',
        'Boldness has genius, power, and magic in it.',
        'Breathe deeply and let go.',
    ],
    // Continue for other letters as needed
};

// Variables to handle pagination and search
let currentPage = 1;
let quotesPerPage = 100;
let currentQuotes = [];

// Function to display quotes based on the selected letter
function showQuotes(letter) {
    // Hide the intro section and show the quotes section
    document.getElementById('intro-section').style.display = 'none';
    document.getElementById('quotes-section').style.display = 'block';

    // Set the quotes for the selected letter
    currentQuotes = quotes[letter] || [];
    currentPage = 1; // Reset to the first page
    displayPaginatedQuotes();
}

// Function to display the quotes for the current page
function displayPaginatedQuotes() {
    const quotesList = document.getElementById('quotes-list');
    quotesList.innerHTML = ''; // Clear existing quotes

    // Get the quotes for the current page
    const startIndex = (currentPage - 1) * quotesPerPage;
    const endIndex = Math.min(startIndex + quotesPerPage, currentQuotes.length);
    const paginatedQuotes = currentQuotes.slice(startIndex, endIndex);

    // Display the paginated quotes
    paginatedQuotes.forEach((quote) => {
        const li = document.createElement('li');
        li.textContent = quote;
        quotesList.appendChild(li);
    });

    // Update pagination controls
    updatePaginationControls();
}

// Function to create and display pagination controls
function updatePaginationControls() {
    const paginationControls = document.getElementById('pagination-controls');
    paginationControls.innerHTML = ''; // Clear existing controls

    const totalPages = Math.ceil(currentQuotes.length / quotesPerPage);

    console.log('Total Pages:', totalPages); // Debugging line

    // Only show pagination if more than one page exists
    if (totalPages > 1) {
        for (let i = 1; i <= totalPages; i++) {
            const button = document.createElement('button');
            button.textContent = i;
            if (i === currentPage) {
                button.classList.add('active');  // Only add 'active' class for the current page
            }
            button.addEventListener('click', () => {
                currentPage = i;
                displayPaginatedQuotes();
            });
            paginationControls.appendChild(button);
        }
    }
}


// Function to filter quotes based on a search term
function searchQuotes() {
    const searchTerm = document.getElementById('search-input').value.toLowerCase();
    
    // Filter current quotes by search term
    const filteredQuotes = currentQuotes.filter(quote => 
        quote.toLowerCase().includes(searchTerm)
    );
    
    // Update quotes list based on the search result
    displayFilteredQuotes(filteredQuotes);
}

// Function to display filtered quotes
function displayFilteredQuotes(filteredQuotes) {
    const quotesList = document.getElementById('quotes-list');
    quotesList.innerHTML = ''; // Clear existing quotes

    if (filteredQuotes.length > 0) {
        filteredQuotes.forEach((quote) => {
            const li = document.createElement('li');
            li.textContent = quote;
            quotesList.appendChild(li);
        });
    } else {
        // If no quotes match the search term
        const li = document.createElement('li');
        li.textContent = 'No quotes found.';
        quotesList.appendChild(li);
    }

    // Hide pagination controls when search is active
    document.getElementById('pagination-controls').style.display = 'none';
}

// Initialize the default state when the page loads
function init() {
    // Show the introduction section and hide the quotes section initially
    document.getElementById('intro-section').style.display = 'block';
    document.getElementById('quotes-section').style.display = 'none';
}
